package com.johnny.cms.domain;

public class Category {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cate_id
     *
     * @mbggenerated
     */
    private Integer cateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column category.cate_name
     *
     * @mbggenerated
     */
    private String cateName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    public Category(Integer cateId, String cateName) {
        this.cateId = cateId;
        this.cateName = cateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table category
     *
     * @mbggenerated
     */
    public Category() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cate_id
     *
     * @return the value of category.cate_id
     * @mbggenerated
     */
    public Integer getCateId() {
        return cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cate_id
     *
     * @param cateId the value for category.cate_id
     * @mbggenerated
     */
    public void setCateId(Integer cateId) {
        this.cateId = cateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column category.cate_name
     *
     * @return the value of category.cate_name
     * @mbggenerated
     */
    public String getCateName() {
        return cateName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column category.cate_name
     *
     * @param cateName the value for category.cate_name
     * @mbggenerated
     */
    public void setCateName(String cateName) {
        this.cateName = cateName == null ? null : cateName.trim();
    }
}