package com.johnny.cms.domain;

import javax.validation.constraints.Pattern;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_id
     *
     * @mbggenerated
     */
    private Integer proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_name
     *
     * @mbggenerated
     */
    //TODO
    @Pattern(regexp = "(^[a-zA-Z0-9_-]{3,16}$)|(^[\u2E80-\u9FFF]+)"
            , message = "商品名必须是中文开头或者3-16位英文和数字的组合")
    private String proName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_state
     *
     * @mbggenerated
     */
    private String proState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_no
     *
     * @mbggenerated
     */
    //TODO
    @Pattern(regexp = "^[a-zA-Z0-9]{6,10}",
            message = "货号必须是6-10位字母数字的组合")
    private String proNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_price
     *
     * @mbggenerated
     */
    private String proPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pro_number
     *
     * @mbggenerated
     */
    private String proNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.d_id
     *
     * @mbggenerated
     */
    private Integer dId;
    //TODO
    private Category category;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public Product(Integer proId, String proName, String proState, String proNo, String proPrice, String proNumber, Integer dId) {
        this.proId = proId;
        this.proName = proName;
        this.proState = proState;
        this.proNo = proNo;
        this.proPrice = proPrice;
        this.proNumber = proNumber;
        this.dId = dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated
     */
    public Product() {
        super();
    }

    public Category getCategory() {
        return category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_id
     *
     * @return the value of product.pro_id
     * @mbggenerated
     */
    public Integer getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_id
     *
     * @param proId the value for product.pro_id
     * @mbggenerated
     */
    public void setProId(Integer proId) {
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_name
     *
     * @return the value of product.pro_name
     * @mbggenerated
     */
    public String getProName() {
        return proName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_name
     *
     * @param proName the value for product.pro_name
     * @mbggenerated
     */
    public void setProName(String proName) {
        this.proName = proName == null ? null : proName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_state
     *
     * @return the value of product.pro_state
     * @mbggenerated
     */
    public String getProState() {
        return proState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_state
     *
     * @param proState the value for product.pro_state
     * @mbggenerated
     */
    public void setProState(String proState) {
        this.proState = proState == null ? null : proState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_no
     *
     * @return the value of product.pro_no
     * @mbggenerated
     */
    public String getProNo() {
        return proNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_no
     *
     * @param proNo the value for product.pro_no
     * @mbggenerated
     */
    public void setProNo(String proNo) {
        this.proNo = proNo == null ? null : proNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_price
     *
     * @return the value of product.pro_price
     * @mbggenerated
     */
    public String getProPrice() {
        return proPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_price
     *
     * @param proPrice the value for product.pro_price
     * @mbggenerated
     */
    public void setProPrice(String proPrice) {
        this.proPrice = proPrice == null ? null : proPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pro_number
     *
     * @return the value of product.pro_number
     * @mbggenerated
     */
    public String getProNumber() {
        return proNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pro_number
     *
     * @param proNumber the value for product.pro_number
     * @mbggenerated
     */
    public void setProNumber(String proNumber) {
        this.proNumber = proNumber == null ? null : proNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.d_id
     *
     * @return the value of product.d_id
     * @mbggenerated
     */
    public Integer getdId() {
        return dId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.d_id
     *
     * @param dId the value for product.d_id
     * @mbggenerated
     */
    public void setdId(Integer dId) {
        this.dId = dId;
    }
}